// playwright.config.js
import { defineConfig, devices } from '@playwright/test';
import { defineBddConfig } from 'playwright-bdd';
import { config as envConfig } from './config/envConfig.js';

function hhmmssSSS(d = new Date()) {
  const hh = String(d.getHours()).padStart(2, '0');
  const mm = String(d.getMinutes()).padStart(2, '0');
  const ss = String(d.getSeconds()).padStart(2, '0');
  return `${hh}-${mm}-${ss}`;
}

if (!process.env.LOG_RUN_ID) {
  process.env.LOG_RUN_ID = hhmmssSSS();
}

const testDir = defineBddConfig({
  features: [
    'tests/api/features/**/*.feature',
    'tests/ui/features/**/*.feature'
  ],
  steps: [
    'src/steps/api/**/*.steps.js',
    'src/steps/ui/**/*.steps.js',
    'src/fixtures/api/api.fixtures.js',
    'src/fixtures/ui/ui.fixtures.js'
  ],

  // BDD Configurations
  quotes: 'double', // use "string" instead of 'string'
});

export default defineConfig({
  // BDD test directory (generated by playwright-bdd)
  testDir,

  // Test match pattern (generated by playwright-bdd)
  testMatch: '**/*.spec.js',

  timeout: envConfig.timeout.global,
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: envConfig.retry.enabled,
  workers: process.env.CI ? 3 : undefined,

  reporter: [
    ['list'],
    ['./src/reporters/configReporter.js'],

    ['html', {
      open: 'never',
      outputFolder: 'out/playwright-report'
    }],

    ['json', {
      outputFile: 'out/test-results/results.json'
    }],

    ['junit', {
      outputFile: 'out/test-results/junit.xml'
    }]
  ],

  /**
   * Global test settings
   */
  use: {
    ignoreHTTPSErrors: !envConfig.isProduction,
    trace: envConfig.isProduction ? 'retain-on-failure' : 'on-first-retry',
    screenshot: 'only-on-failure',
    video: 'retain-on-failure',
    actionTimeout: envConfig.timeout.request,
  },

  projects: [
    {
      name: 'API Tests - Chromium',
      use: {
        ...devices['Desktop Chrome'],
        baseURL: envConfig.apiBaseUrl,
        extraHTTPHeaders: {
          Accept: 'application/json',
          'Content-Type': 'application/json',
          ...(envConfig.apiKey && { 'X-API-Key': envConfig.apiKey })
        }
      },
      testMatch: /api[\\/].*\.spec\.js/
    },
    {
      name: 'UI Tests - Chromium',
      use: {
        ...devices['Desktop Chrome'],
        baseURL: envConfig.baseUrl,
        trace: envConfig.isProduction ? 'retain-on-failure' : 'off',
        video: envConfig.isProduction ? 'retain-on-failure' : 'off',
        screenshot: 'only-on-failure'
      },
      testMatch: /ui[\\/].*\.spec\.js/
    },
  ],

  // Playwright output (incl. attachments) goes here
  outputDir: 'out/test-results/',
});
